import { defineAsyncComponent, markRaw } from 'vue';

import {
  EventCategoryDrop,
  EventCategoryFilterDrop,
  EventCategoryName,
  EventDto,
  EventFilters,
  EventFormatDrop,
  EventFormatName,
  EventOrganizerDrop,
} from '@/interfaces/event/event.dto';
import {
  UserSubjectDrop,
  UserSubjectFilterDrop,
  UserSubjectName,
} from '@/interfaces/user/user.dto';
import { CommonFilter } from '@/interfaces/common/index.dto';

const IconCommonClock = defineAsyncComponent(() => import('@icons/common/clock.vue'));
const IconCommonCalendar = defineAsyncComponent(() => import('@icons/common/calendar.vue'));

export const EVENT_FILTER_INPUTS = (filters: Record<string, string>) => ({
  id: 'event-filter',
  inputs: [
    {
      grid: '1 / 13',
      id: 'category',
      type: 'selector-single',
      placeholder: '',
      name: 'Категория',
      drop: EventCategoryFilterDrop,
      show: true,
      required: true,
    },
    {
      grid: '1 / 13',
      id: 'organizer',
      type: 'selector-single',
      placeholder: '',
      name: 'Кто проводит',
      drop: EventOrganizerDrop,
      show: true,
      required: true,
    },
    {
      grid: '1 / 13',
      id: 'subject',
      type: 'selector-single',
      placeholder: '',
      name: 'Тематика',
      drop: UserSubjectFilterDrop,
      show: true,
      required: true,
    },
  ],
  data: {
    category: filters.category || CommonFilter.ALL,
    organizer: filters.organizer || CommonFilter.ALL,
    subject: filters.subject || CommonFilter.ALL,
  } as EventFilters,
  classList: 'flex-column',
});

export const EVENT_CREATE_INPUTS = (event?: EventDto | null) => ({
  id: 'event-create',
  inputs: [
    {
      grid: '1 / 13',
      id: 'cover',
      type: 'image',
      placeholder: '',
      name: 'Обложка',
      show: true,
      required: false,
    },
    {
      grid: '1 / 7',
      id: 'name',
      type: 'text',
      placeholder: 'Лаконичное название, отражающее суть.',
      name: 'Название мероприятия',
      show: true,
      required: true,
    },
    {
      grid: '7 / 13',
      id: 'format',
      type: 'drop-single',
      placeholder: 'Выбрать...',
      name: 'Формат',
      drop: EventFormatDrop,
      drop_enum: EventFormatName,
      show: true,
      required: true,
    },
    {
      grid: '7 / 13',
      id: 'subject',
      type: 'selector-single',
      placeholder: '',
      name: 'Тематика',
      drop: UserSubjectDrop,
      drop_enum: UserSubjectName,
      show: true,
      required: true,
    },
    {
      grid: '1 / 7',
      grid_row: '3 / 6',
      id: 'content',
      type: 'textarea',
      placeholder: 'Опишите, чем планируете заниматься на мероприятии и о чем будете рассказывать.',
      name: 'Описание',
      show: true,
      required: true,
    },
    {
      grid: '7 / 10',
      id: 'startedAt',
      type: 'datetime',
      placeholder: '',
      name: 'Дата и время начала',
      show: true,
      required: true,
      icon: markRaw(IconCommonCalendar),
    },
    {
      grid: '10 / 13',
      id: 'period',
      type: 'text',
      placeholder: '45 минут',
      name: 'Продолжительность, мин.',
      mask: '###',
      show: true,
      required: true,
      icon: markRaw(IconCommonClock),
    },
    {
      grid: '7 / 10',
      id: 'minMembers',
      type: 'text',
      placeholder: 'Мин: 10',
      name: 'Мин. участников',
      mask: '####',
      show: true,
      required: true,
    },
    {
      grid: '10 / 13',
      id: 'maxMembers',
      type: 'text',
      placeholder: 'Макс: 1000',
      name: 'Макс. участников',
      mask: '####',
      show: true,
      required: true,
    },
    {
      grid: '1 / 7',
      grid_row: '6 / 8',
      id: 'additional',
      type: 'textarea',
      placeholder: 'Форма, инвентарь, оплата за материалы',
      name: 'Дополнительные условия',
      show: true,
      required: false,
      prompt: `Внимание! Все услуги для участников бесплатные, если вы осуществляете сбор денег, то он
      может быть направлен только на материалы или аренду. Администрация в любой момент может
      запросить чеки`,
    },
    {
      grid: '7 / 13',
      id: 'category',
      type: 'drop-single',
      placeholder: 'Выберите тип мероприятия',
      name: 'Площадка',
      drop: EventCategoryDrop,
      drop_enum: EventCategoryName,
      show: true,
      required: true,
    },
    {
      grid: '7 / 13',
      id: 'link',
      type: 'text',
      placeholder: 'Укажите ссылку на мероприятие',
      name: '',
      show: false,
      required: false,
    },
    {
      grid: '7 / 13',
      id: 'place',
      type: 'text',
      placeholder: 'Укажите место проведения мероприятия',
      name: '',
      show: false,
      required: false,
    },
  ],
  data: {
    name: '',
    format: '',
    content: '',
    minMembers: '',
    maxMembers: '',
    startedAt: '',
    period: '',
    category: '',
    link: '',
    place: '',
  } as any,
});
